logging.level:
  com.nurkiewicz: TRACE

elasticsearch:
  hosts:
    - http://localhost:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000

spring.metrics.export.graphite:
  host: 127.0.0.1
  port: 2003
  protocol: Plaintext
  step: PT1S
